> ** Feature Normalize ** -  standardization

\begin{equation}
X'_j = \frac{x_j - \mu_j}{\sigma_j}
\end{equation}

In [203]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#pd.set_option('display.precision', 2)
#pd.set_option('chop_threshold', 0.005)

In [204]:
df = pd.read_csv('../data/iris.data', header=None)

In [205]:
X = df.iloc[:10, :4].values

In [206]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [207]:
y = df.iloc[:10, 4]
y = np.where(y.values == 'Iris-setosa', -1, 1)
y

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [208]:
X.mean(axis=0)

array([4.86, 3.31, 1.45, 0.22])

In [209]:
X.std(axis=0)

array([0.2764055 , 0.29137605, 0.10246951, 0.07483315])

In [210]:
X_std = np.copy(X)
X_std = (X - X.mean()) / X.std()
r = np.random.permutation(len(y))
X, X_std

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1]]),
 array([[ 1.48174374,  0.58371723, -0.59494256, -1.26846245],
        [ 1.36949043,  0.30308395, -0.59494256, -1.26846245],
        [ 1.25723711,  0.41533726, -0.65106922, -1.26846245],
        [ 1.20111046,  0.3592106 , -0.53881591, -1.26846245],
        [ 1.42561708,  0.63984389, -0.59494256, -1.26846245],
        [ 1.65012371,  0.80822386, -0.42656259, -1.15620913],
        [ 1.20111046,  0.52759057, -0.59494256, -1.21233579],
        [ 1.42561708,  0.52759057, -0.53881591, -1.26846245],
        [ 1.08885714,  0.24695729, -0.59494256, -1.26846245],
        [ 1.36949043,  0.3592106 , -0.53881591, -1.3245891 ]]))

In [211]:
w = np.zeros(5)
eta = 0.01
n_iter = 15
costs = []

### Repeat >>>>

In [212]:
for _ in (range(0, n_iter)):
    output = np.dot(X_std, w[1:]) + w[0]
    errors = (y - output)
    w[1:] += eta * X_std.T.dot(errors)
    w[0] += eta * errors.sum()
    cost = 0.5 * (errors ** 2).sum()
    costs.append(cost)

costs

[5.0,
 1.2809154613705256,
 0.334500065382874,
 0.09362361367879285,
 0.03228029158038457,
 0.016621674048006865,
 0.012588438012546766,
 0.011513781727635328,
 0.011192331879000175,
 0.011062902322533569,
 0.010982689873625436,
 0.010915353877658239,
 0.010851644354666727,
 0.010789204888600258,
 0.010727433232641258]

## Large scale machine learning and stochastic gradient descent

In [213]:
# Re-initialize
cost = []
w = np.zeros(5)

In [217]:
r = np.random.permutation(len(y))
X_std = X_std[r]

In [238]:
feedIter = zip(X_std, y)
xi, target = feedIter.__next__()
output = np.dot(xi, w[1:]) + w[0]
error = (target - output)
w[1:] += eta * xi.dot(error)
w[0] += eta * error
cost = 0.5 * error**2
cost

0.10970623337506308